Async
DBCDK/faythe pull request #94
Opened 2024-10-16 09:23 UTC by johanot

2024-10-18 08:58 UTC, srhb commented
I pushed some commits. I think it _eventually_ works most of the time now :tm: 

- I think the touch-rewrite was only half-done, think i fixed it in a sensible way.
- I fixed metrics so it doesn't spawn a runtime (inside the runtime)
- I enabled the secondary vault monitor config test.

There's some issues I am still debugging before I think it's ready for review by someone wiser than me. Writing them down here so I can keep track of where I am.

1. something is spamming
```
vm-test-run-faythe-vault-test> client # [   32.872869] faythe[881]: [2024-10-18T08:52:39Z ERROR rustify::client] error=Server returned error
vm-test-run-faythe-vault-test> client # [   32.873456] faythe[881]: [2024-10-18T08:52:39Z ERROR rustify::endpoint] error=Server returned error
vm-test-run-faythe-vault-test> client # [   32.874041] faythe[881]: [2024-10-18T08:52:39Z ERROR vaultrs::api] Detected errors in API response: []
vm-test-run-faythe-vault-test> client # [   32.874639] faythe[881]: [2024-10-18T08:52:39Z ERROR vaultrs::kv2] error=The Vault server returned an error (status code 404)
```

Haven't found out what yet. Probably part of the raw cert check.

2. faythe appears to set up too many challenges according to pebble. I've seen 5 challenges in the db at one time.

3. faythe appears to set up the wrong dns proofs sometime, getting stuck validating internally. Unsure why this happens.

4. sometimes there's nonce errors in the AcmeClient. I think this may simply be because of the default pebble setup `vm-test-run-faythe-vault-test> acme # [    5.144768] pebble[662]: Pebble 2024/10/18 08:52:12 Configured to reject 5% of good nonces` -- but we should handle this (and maybe that'll fix some other issues? I do think I'm seeing them too often for the 5% to be the only reason)

2024-10-19 14:25 UTC, johanot commented on src/vault.rs
> -                    > chrono::Duration::milliseconds(
@srhb ... understand you fixed some issue with "raw_read", but... it looks like - from this diff - that the logic handling should_retry time-diff totally disappeared? Causing "RecentlyTouched" to never be constructed. I would imagine this causing a lot of concurrent issuing attempt. Maybe this explain some of the other problems you are describing?

2024-10-19 15:15 UTC, johanot commented on src/vault.rs
> -                    > chrono::Duration::milliseconds(
Having #95 could have CI-caught the unused error variant :)

2024-11-19 15:56 UTC, srhb commented
I've fixed the remaining _known_ bugs in our fork of acme_lib (tmp commit added while the fork change gets approved) -- at least I can now consistently run the test without failures...

2025-01-02 14:48 UTC, srhb commented on src/vault.rs
> -                    > chrono::Duration::milliseconds(
:zombie_woman: wdyt, did I fix it, or should I go back and try to recreate from where you were? It might be hard to follow at this point, months later :sweat:

2025-01-09 08:18 UTC, cafkafk requested changes

2025-01-09 08:18 UTC, cafkafk commented on src/monitor.rs
> +    //#[test]
If we comment out this test, we should at least give an explanation for why where doing it, and when we can enable it again

2025-01-09 12:40 UTC, srhb commented on src/monitor.rs
> +    //#[test]
OK, I'll try to figured out why it bork.

2025-01-15 07:35 UTC, cafkafk approved these changes

2025-01-15 07:35 UTC, cafkafk commented on src/monitor.rs
> +    //#[test]
I think removal may make more sense given it's never worked anyways, but that can be a follow up commit.

2025-01-15 07:40 UTC, cafkafk commented on src/vault.rs
> -                    > chrono::Duration::milliseconds(
Considering this PR is blocking for any other changes, I think it's reasonable to resolve this conversation and then corrections can be made in a follow up PR. Specially considering johanots point that certain checks may have caught this in the first place, those checks can only come after we merge this.

May also be a cautionary tale of not sending large patchsets in the future, smaller merges faster.

2025-01-15 07:40 UTC, merged